<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Assets\wolfnet-radio.ico</ApplicationIcon>
    <AssemblyName>WolfNETRadio</AssemblyName>
    <RootNamespace>WolfNETRadio</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Concentus" Version="2.2.2" />
    <PackageReference Include="Concentus.OggFile" Version="1.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\wolfnet-radio.ico" />
    <Resource Include="Assets\wolfnet-logo.png" />
  </ItemGroup>
</Project>
